#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
## herbstluftwm config for Archcraft

## Configurations --------------------------------------------#

hc() {
    herbstclient "$@"
}

hc emit_hook reload

## Autostart -------------------------------------------------#

bash ~/.config/herbstluftwm/bin/autostart.sh
nitrogen --restore

## keybindings -----------------------------------------------#

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4   # Use the super key as the main modifier
Alt=Mod1   # Use alt as another modifier

# terminals
TERMINAL="$HOME/.config/herbstluftwm/bin/herbterm.sh"
hc keybind $Mod-Return spawn "$TERMINAL"
# hc keybind $Mod-Shift-Return spawn "$TERMINAL" -f
# hc keybind $Mod-t spawn "$TERMINAL" -s

# applications
FILE_MANAGER='thunar'
TEXT_EDITOR='code'
WEB_BROWSER='waterfox-g4'
hc keybind $Mod-v spawn "$TEXT_EDITOR"
hc keybind $Mod-Shift-f spawn "$FILE_MANAGER"
hc keybind $Mod-Shift-w spawn "$WEB_BROWSER"

# rofi menus
hc keybind $Alt-F1 spawn ~/.config/herbstluftwm/rofi/bin/launcher
hc keybind $Mod-n spawn ~/.config/herbstluftwm/rofi/bin/network_menu
hc keybind $Mod-x spawn ~/.config/herbstluftwm/rofi/bin/powermenu
hc keybind $Mod-m spawn ~/.config/herbstluftwm/rofi/bin/mpd
hc keybind $Mod-Print spawn ~/.config/herbstluftwm/rofi/bin/screenshot
# hc keybind $Mod-r spawn ~/.config/herbstluftwm/rofi/bin/asroot
hc keybind $Mod-w spawn ~/.config/herbstluftwm/rofi/bin/windows

# function keys
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -5%
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind XF86AudioPlay 			spawn playerctl play-pause
hc keybind XF86AudioStop 			spawn playerctl play-pause
# hc keybind XF86MonBrightnessUp 		spawn "brightness" "--inc"
# hc keybind XF86MonBrightnessDown 	spawn "brightness" "--dec"
# hc keybind XF86AudioRaiseVolume 	spawn "volume" "--inc"
# hc keybind XF86AudioLowerVolume 	spawn "volume" "--dec"
# hc keybind XF86AudioMute 			spawn "volume" "--toggle"
# hc keybind XF86AudioNext 			spawn "mpc next"
# hc keybind XF86AudioPrev 			spawn "mpc prev"
# hc keybind XF86AudioPlay 			spawn "mpc toggle"
# hc keybind XF86AudioStop 			spawn "mpc stop"

# screenshots
hc keybind Print 					spawn "takeshot" "--now"
# hc keybind $Mod-Print 				spawn "takeshot" "--in5"
hc keybind Shift-Print 				spawn "takeshot" "--in10"
hc keybind Control-Print 			spawn "takeshot" "--win"
hc keybind $Mod-Control-Print 		spawn "takeshot" "--area"

# misc
hc keybind $Mod-p 					spawn "color-gpick"

# window manager
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind Control-$Alt-l 			spawn "betterlockscreen" "--lock"
hc keybind Control-$Alt-Escape 		spawn xkill

# focusing clients, basic movement in tiling and floating mode
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# splitting frames, create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-s split explode
hc keybind $Mod-r remove

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-b cycle
hc keybind $Mod-i jumpto urgent

## Mouse -----------------------------------------------------#

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

## Tags ------------------------------------------------------#

tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

## Layouts ---------------------------------------------------#

hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-space set_attr clients.focus.floating toggle
hc keybind $Mod-Control-space floating toggle

hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized

hc keybind $Mod-g pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

## Window rules ----------------------------------------------#

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class~'(alacritty-float)' focus=on floating=on
hc rule class~'(Pcmanfm|Onboard|Yad)' focus=on floating=on
hc rule class~'(Lxappearance|Nitrogen)' focus=on floating=on
hc rule class~'(Pavucontrol|Xfce4-power-manager-settings|Nm-connection-editor)' focus=on floating=on
hc rule class~'(feh|Viewnior|Gpicview|Gimp|MPlayer)' focus=on floating=on
hc rule class~'(Kvantum Manager|qt5ct)' focus=on floating=on
hc rule class~'(VirtualBox Manager|qemu|Qemu-system-x86_64)' focus=on floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

## Theme -----------------------------------------------------#

# the frame
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#D97E96'
hc attr theme.normal.color '#333'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.active.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.color '#D97E96'
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#3E4A00'
#hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

hc set window_gap 0
hc set frame_padding 10
hc set smart_window_surroundings false
hc set smart_frame_surroundings false
hc set mouse_recenter_gap 0
